# Generated by Django 3.2.21 on 2023-11-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('quantity', models.PositiveIntegerField(unique=True)),
                ('min_stock', models.PositiveBigIntegerField(default=100)),
                ('cost_price', models.PositiveIntegerField(default=3500)),
                ('selling_price', models.PositiveIntegerField(default=4000)),
            ],
        ),
    ]
